language: c
before_script:
  - chmod +x tools/pawn/pawncc
script:
  - cd gamemodes
  - export LD_LIBRARY_PATH="../tools/pawn:$LD_LIBRARY_PATH"
  - ../tools/pawn/pawncc grgserver.pwn -i../includes -\; -\(